//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Board.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Board.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add card.
        /// </summary>
        public static string Column_AddCard {
            get {
                return ResourceManager.GetString("Column_AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more.
        /// </summary>
        public static string Column_LoadMore {
            get {
                return ResourceManager.GetString("Column_LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete column.
        /// </summary>
        public static string Column_Menu_DeleteColumn {
            get {
                return ResourceManager.GetString("Column_Menu_DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit column.
        /// </summary>
        public static string Column_Menu_EditColumn {
            get {
                return ResourceManager.GetString("Column_Menu_EditColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More cards.
        /// </summary>
        public static string Column_MoreCards {
            get {
                return ResourceManager.GetString("Column_MoreCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit column.
        /// </summary>
        public static string ColumnEditor_Title_Edit {
            get {
                return ResourceManager.GetString("ColumnEditor_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New column.
        /// </summary>
        public static string ColumnEditor_Title_New {
            get {
                return ResourceManager.GetString("ColumnEditor_Title_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name.
        /// </summary>
        public static string ColumnEditorWindow_Label_ColumnName {
            get {
                return ResourceManager.GetString("ColumnEditorWindow_Label_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit displayed entries.
        /// </summary>
        public static string ColumnEditorWindow_Label_LimitDefaultEntryCount {
            get {
                return ResourceManager.GetString("ColumnEditorWindow_Label_LimitDefaultEntryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Comment_Footer_Delete {
            get {
                return ResourceManager.GetString("Comment_Footer_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Comment_Footer_Edit {
            get {
                return ResourceManager.GetString("Comment_Footer_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commented.
        /// </summary>
        public static string Comment_Header_Commented {
            get {
                return ResourceManager.GetString("Comment_Header_Commented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on .
        /// </summary>
        public static string Comment_Header_On {
            get {
                return ResourceManager.GetString("Comment_Header_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string DatesPopup_Label_EndDate {
            get {
                return ResourceManager.GetString("DatesPopup_Label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string DatesPopup_Label_StartDate {
            get {
                return ResourceManager.GetString("DatesPopup_Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string DefaultDialogTitle {
            get {
                return ResourceManager.GetString("DefaultDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        public static string DefaultFilter {
            get {
                return ResourceManager.GetString("DefaultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string DefaultMessageboxTitle {
            get {
                return ResourceManager.GetString("DefaultMessageboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete permanently (this cannot be reversed!).
        /// </summary>
        public static string DeleteDialogWindow_Label_DeletePermanently {
            get {
                return ResourceManager.GetString("DeleteDialogWindow_Label_DeletePermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open table background.
        /// </summary>
        public static string Dialog_OpenTableBackground_Title {
            get {
                return ResourceManager.GetString("Dialog_OpenTableBackground_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall project files.
        /// </summary>
        public static string Dialog_OpenWall_ProjectFilterDesc {
            get {
                return ResourceManager.GetString("Dialog_OpenWall_ProjectFilterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open wall.
        /// </summary>
        public static string Dialog_OpenWall_Title {
            get {
                return ResourceManager.GetString("Dialog_OpenWall_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Entry_Menu_Delete {
            get {
                return ResourceManager.GetString("Entry_Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Entry_Menu_Show {
            get {
                return ResourceManager.GetString("Entry_Menu_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string EntryEditor_Button_AddDates {
            get {
                return ResourceManager.GetString("EntryEditor_Button_AddDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string EntryEditor_Button_AddTags {
            get {
                return ResourceManager.GetString("EntryEditor_Button_AddTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string EntryEditor_Header_Comments {
            get {
                return ResourceManager.GetString("EntryEditor_Header_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EntryEditor_Header_Description {
            get {
                return ResourceManager.GetString("EntryEditor_Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new comment.
        /// </summary>
        public static string EntryEditor_Label_AddNewComment {
            get {
                return ResourceManager.GetString("EntryEditor_Label_AddNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag.
        /// </summary>
        public static string EntryEditor_Label_AddTag {
            get {
                return ResourceManager.GetString("EntryEditor_Label_AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to card.
        /// </summary>
        public static string EntryEditor_Label_AddToCard {
            get {
                return ResourceManager.GetString("EntryEditor_Label_AddToCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string EntryEditor_Label_Dates {
            get {
                return ResourceManager.GetString("EntryEditor_Label_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string EntryEditor_Label_Done {
            get {
                return ResourceManager.GetString("EntryEditor_Label_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EntryEditor_Label_EndDate {
            get {
                return ResourceManager.GetString("EntryEditor_Label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string EntryEditor_Label_StartDate {
            get {
                return ResourceManager.GetString("EntryEditor_Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string EntryEditor_Label_Tags {
            get {
                return ResourceManager.GetString("EntryEditor_Label_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In column .
        /// </summary>
        public static string EntryEditor_Title_InColumn {
            get {
                return ResourceManager.GetString("EntryEditor_Title_InColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images (*.png;*.jpg;*.jpeg;*.bmp)|*.png;*.jpg;*.jpeg;*.bmp.
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete board.
        /// </summary>
        public static string MainWindow_RibbonButton_DeleteBoard {
            get {
                return ResourceManager.GetString("MainWindow_RibbonButton_DeleteBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit board.
        /// </summary>
        public static string MainWindow_RibbonButton_EditBoard {
            get {
                return ResourceManager.GetString("MainWindow_RibbonButton_EditBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string MainWindow_RibbonButton_Editor {
            get {
                return ResourceManager.GetString("MainWindow_RibbonButton_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New board.
        /// </summary>
        public static string MainWindow_RibbonButton_NewBoard {
            get {
                return ResourceManager.GetString("MainWindow_RibbonButton_NewBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New wall.
        /// </summary>
        public static string MainWindow_RibbonButton_NewWall {
            get {
                return ResourceManager.GetString("MainWindow_RibbonButton_NewWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open wall.
        /// </summary>
        public static string MainWindow_RibbonButton_OpenWall {
            get {
                return ResourceManager.GetString("MainWindow_RibbonButton_OpenWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string MainWindow_RibbonGroup_Board {
            get {
                return ResourceManager.GetString("MainWindow_RibbonGroup_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_RibbonGroup_File {
            get {
                return ResourceManager.GetString("MainWindow_RibbonGroup_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string MainWindow_RibbonGroup_Tags {
            get {
                return ResourceManager.GetString("MainWindow_RibbonGroup_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainWindow_RibbonTab_Home {
            get {
                return ResourceManager.GetString("MainWindow_RibbonTab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open link {0}!.
        /// </summary>
        public static string Message_CannotOpenLink {
            get {
                return ResourceManager.GetString("Message_CannotOpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete column {0}?.
        /// </summary>
        public static string Message_ColumnDeletion {
            get {
                return ResourceManager.GetString("Message_ColumnDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete comment from {0}?.
        /// </summary>
        public static string Message_CommentDeletion {
            get {
                return ResourceManager.GetString("Message_CommentDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete entry {0}?.
        /// </summary>
        public static string Message_EntryDeletion {
            get {
                return ResourceManager.GetString("Message_EntryDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image file!.
        /// </summary>
        public static string Message_InvalidImageFile {
            get {
                return ResourceManager.GetString("Message_InvalidImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete board {0}?.
        /// </summary>
        public static string Message_TableDeletion {
            get {
                return ResourceManager.GetString("Message_TableDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete tag {0}?.
        /// </summary>
        public static string Message_TagDeletion {
            get {
                return ResourceManager.GetString("Message_TagDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose storage method:.
        /// </summary>
        public static string NewWallWindow_Label_ChooseStorageMethod {
            get {
                return ResourceManager.GetString("NewWallWindow_Label_ChooseStorageMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite.
        /// </summary>
        public static string NewWallWindow_Label_SQLite {
            get {
                return ResourceManager.GetString("NewWallWindow_Label_SQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is stored locally without collaboration option..
        /// </summary>
        public static string NewWallWindow_Label_SQLite_Description {
            get {
                return ResourceManager.GetString("NewWallWindow_Label_SQLite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New wall.
        /// </summary>
        public static string NewWallWindow_Title {
            get {
                return ResourceManager.GetString("NewWallWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure SQLite.
        /// </summary>
        public static string SQLiteConfigWindow_GroupBox_ConfigureSQLite {
            get {
                return ResourceManager.GetString("SQLiteConfigWindow_GroupBox_ConfigureSQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string SQLiteConfigWindow_Label_Location {
            get {
                return ResourceManager.GetString("SQLiteConfigWindow_Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall name.
        /// </summary>
        public static string SQLiteConfigWindow_Label_WallName {
            get {
                return ResourceManager.GetString("SQLiteConfigWindow_Label_WallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure SQLite.
        /// </summary>
        public static string SQLiteConfigWindow_Title {
            get {
                return ResourceManager.GetString("SQLiteConfigWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New column....
        /// </summary>
        public static string Table_Command_NewColumn {
            get {
                return ResourceManager.GetString("Table_Command_NewColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit board.
        /// </summary>
        public static string TableEditor_Title_Edit {
            get {
                return ResourceManager.GetString("TableEditor_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New board.
        /// </summary>
        public static string TableEditor_Title_New {
            get {
                return ResourceManager.GetString("TableEditor_Title_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board name.
        /// </summary>
        public static string TableEditorWindow_Label_BoardName {
            get {
                return ResourceManager.GetString("TableEditorWindow_Label_BoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string TagEditor_Label_Color {
            get {
                return ResourceManager.GetString("TagEditor_Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TagEditor_Label_Name {
            get {
                return ResourceManager.GetString("TagEditor_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tag.
        /// </summary>
        public static string TagEditor_Title_Edit {
            get {
                return ResourceManager.GetString("TagEditor_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tag.
        /// </summary>
        public static string TagEditor_Title_New {
            get {
                return ResourceManager.GetString("TagEditor_Title_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tag.
        /// </summary>
        public static string TagListWindow_Button_NewTag {
            get {
                return ResourceManager.GetString("TagListWindow_Button_NewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagListWindow_GroupBox_Tags {
            get {
                return ResourceManager.GetString("TagListWindow_GroupBox_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagListWindow_Title_Tags {
            get {
                return ResourceManager.GetString("TagListWindow_Title_Tags", resourceCulture);
            }
        }
    }
}
